---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - deployment-fdk-maskinporten-exchange.yaml
  - service-fdk-maskinporten-exchange.yaml
images:
  - name: fdk-maskinporten-exchange
    newName: ghcr.io/informasjonsforvaltning/fdk-maskinporten-exchange
    newTag: $(GIT_COMMIT_SHA)
