---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-maskinporten-exchange
  labels:
    app: fdk-maskinporten-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-maskinporten-exchange
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-maskinporten-exchange
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: fdk-maskinporten-exchange
          env:
            - name: MASKINPORTEN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_CLIENT_ID
            - name: MASKINPORTEN_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_KEY_ID
            - name: MASKINPORTEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_PRIVATE_KEY
            - name: MASKINPORTEN_ISSUER
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_ISSUER
                  optional: true
            - name: MASKINPORTEN_TOKEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_TOKEN_ENDPOINT
                  optional: true
            - name: MASKINPORTEN_JWKS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_JWKS_ENDPOINT
                  optional: true
            - name: MASKINPORTEN_SCOPE
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: MASKINPORTEN_SCOPE
                  optional: true
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: fdk-maskinporten-exchange-staging
                  key: LOG_LEVEL
                  optional: true
          image: fdk-maskinporten-exchange
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
