name: Deploy to prod

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build-fdk-maskinporten-exchange:
    name: Build on push to main
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: fdk-maskinporten-exchange
      environment: prod
      gh_environment: prod
      java_version: '25'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to prod environment
    needs: [ build-fdk-maskinporten-exchange ]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: fdk-maskinporten-exchange
      environment: prod
      gh_environment: prod
      cluster: digdir-fdk-prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
